import { addDays, subDays } from 'date-fns'
import { createDefaultProposalTemplates } from '@/features/proposals/templates'
import { generateId } from '@/lib/id'
import { CURRENT_SCHEMA_VERSION } from '@/schemas/workspace'
import type { Workspace } from '@/types/entities'

/** Espace de travail vide — c'est l'état de départ réel d'une nouvelle installation. */
export function createEmptyWorkspace(): Workspace {
  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    businessConfig: {
      id: generateId(),
      companyName: '',
      vatStatus: 'ne_sait_pas_encore',
      currency: 'EUR',
    },
    userProfile: {
      id: generateId(),
      displayName: '',
      onboarded: false,
    },
    weddings: [],
    vendors: [],
    vendorWeddingLinks: [],
    tasks: [],
    timelineEvents: [],
    expenses: [],
    scopeChanges: [],
    proposals: [],
    soldServices: [],
    proposalTemplates: createDefaultProposalTemplates(),
    clientDecisions: [],
    invoices: [],
    equipmentItems: [],
    closingSessions: [],
    uiPreferences: { theme: 'system' },
    ignoredConflictIds: [],
  }
}

/**
 * Données fictives — jamais chargées automatiquement dans le workspace
 * persisté. Utilisée uniquement via une action explicite ("Charger des
 * données de démonstration") pour ne pas mélanger démo et données réelles.
 */
export function createDemoWorkspace(): Workspace {
  const today = new Date()
  const iso = (d: Date) => d.toISOString()

  const weddings: Workspace['weddings'] = [
    {
      id: 'w1',
      coupleName: 'Camille & Antoine',
      date: iso(addDays(today, 12)),
      venue: 'Domaine de la Prairie, Rambouillet',
      soldAmount: 8400,
      clientBudget: 9000,
      status: 'semaine_j',
      archived: false,
      vendorIds: ['v1', 'v2', 'v4'],
      // Marge plus stricte que la valeur par défaut (15 min) : démontre le réglage par mariage.
      minBufferMinutes: 45,
      createdAt: iso(subDays(today, 210)),
      updatedAt: iso(subDays(today, 1)),
    },
    {
      id: 'w2',
      coupleName: 'Lina & Hugo',
      date: iso(addDays(today, 41)),
      venue: 'Château de Villette',
      soldAmount: 15200,
      clientBudget: 14000,
      status: 'en_preparation',
      archived: false,
      vendorIds: ['v2', 'v3'],
      createdAt: iso(subDays(today, 150)),
      updatedAt: iso(subDays(today, 3)),
    },
    {
      id: 'w3',
      coupleName: 'Sofia & Marc',
      date: iso(addDays(today, 96)),
      venue: 'Abbaye de Vaux-de-Cernay',
      soldAmount: 11000,
      clientBudget: 11000,
      status: 'signe',
      archived: false,
      vendorIds: ['v1'],
      createdAt: iso(subDays(today, 60)),
      updatedAt: iso(subDays(today, 14)),
    },
    {
      id: 'w4',
      coupleName: 'Nora & Thibault',
      date: iso(addDays(today, 8)),
      venue: 'Le Clos des Cèdres, Chantilly',
      soldAmount: 6800,
      clientBudget: 6500,
      status: 'semaine_j',
      archived: false,
      vendorIds: ['v3'],
      createdAt: iso(subDays(today, 190)),
      updatedAt: iso(subDays(today, 2)),
    },
  ]

  const vendors: Workspace['vendors'] = [
    {
      id: 'v1',
      name: 'Julien Roussel',
      company: 'Traiteur Les Saveurs',
      category: 'Traiteur',
      email: 'contact@lessaveurs.fr',
      weddingIds: ['w1', 'w3'],
    },
    {
      id: 'v2',
      name: 'Bastien Caron',
      company: 'DJ Bastien Prod',
      category: 'DJ',
      phone: '06 12 34 56 78',
      weddingIds: ['w1', 'w2'],
    },
    {
      id: 'v3',
      name: 'Camille Fontaine',
      company: 'Fleurs de Mars',
      category: 'Fleuriste',
      email: 'hello@fleursdemars.fr',
      weddingIds: ['w2', 'w4'],
    },
    {
      id: 'v4',
      name: 'Antoine Lefèvre',
      company: 'Focus Studio',
      category: 'Photographe',
      email: 'antoine@focusstudio.fr',
      phone: '06 98 76 54 32',
      weddingIds: ['w1'],
    },
  ]

  /**
   * Un même prestataire (v1, v2, v3) est ici volontairement lié à 2 mariages
   * chacun, avec un coût DIFFÉRENT par mariage — ça démontre que le modèle
   * ne partage plus le coût entre mariages (cf. migration v3→v4). Aucun de
   * ces liens n'a needsCostReview : ce sont des liens créés normalement, pas
   * issus d'une migration.
   */
  const vendorWeddingLinks: Workspace['vendorWeddingLinks'] = [
    { id: 'vwl1', vendorId: 'v1', weddingId: 'w1', status: 'confirme', arrivalTime: '10:00', estimatedCost: 4200, actualCost: 4200 },
    { id: 'vwl2', vendorId: 'v1', weddingId: 'w3', status: 'devis_recu', estimatedCost: 3800, actualCost: 3800 },
    { id: 'vwl3', vendorId: 'v2', weddingId: 'w1', status: 'a_contacter', estimatedCost: 1100 },
    { id: 'vwl4', vendorId: 'v2', weddingId: 'w2', status: 'confirme', arrivalTime: '18:00', estimatedCost: 950 },
    { id: 'vwl5', vendorId: 'v3', weddingId: 'w2', status: 'devis_recu', estimatedCost: 3200 },
    { id: 'vwl6', vendorId: 'v3', weddingId: 'w4', status: 'confirme', arrivalTime: '14:00', estimatedCost: 2600 },
    { id: 'vwl7', vendorId: 'v4', weddingId: 'w1', status: 'contacte', arrivalTime: '09:30', estimatedCost: 1800 },
  ]

  const tasks: Workspace['tasks'] = [
    {
      id: 't1',
      title: 'Confirmer le plan de table final avec le traiteur',
      description: 'Valider le nombre de tables et les placements avant impression.',
      status: 'a_faire',
      priority: 'haute',
      weddingId: 'w1',
      vendorId: 'v1',
      dueDate: iso(today),
      postponedCount: 0,
      postponeHistory: [],
      source: 'manual',
      createdAt: iso(subDays(today, 5)),
      updatedAt: iso(subDays(today, 5)),
    },
    {
      id: 't2',
      title: 'Réceptionner les compositions florales',
      status: 'a_faire',
      priority: 'normale',
      weddingId: 'w4',
      vendorId: 'v3',
      dueDate: iso(today),
      postponedCount: 0,
      postponeHistory: [],
      source: 'manual',
      createdAt: iso(subDays(today, 3)),
      updatedAt: iso(subDays(today, 3)),
    },
    {
      id: 't3',
      title: 'Valider le plan lumière avec le DJ',
      status: 'en_cours',
      priority: 'urgente',
      weddingId: 'w1',
      vendorId: 'v2',
      dueDate: iso(subDays(today, 1)),
      postponedCount: 1,
      postponeHistory: [
        {
          fromDate: iso(subDays(today, 4)),
          toDate: iso(subDays(today, 1)),
          reason: 'DJ indisponible pour un appel avant vendredi',
          createdAt: iso(subDays(today, 4)),
        },
      ],
      source: 'manual',
      createdAt: iso(subDays(today, 20)),
      updatedAt: iso(subDays(today, 4)),
    },
    {
      id: 't4',
      title: "Relancer la mairie pour l'autorisation d'installation",
      status: 'en_attente',
      priority: 'haute',
      weddingId: 'w2',
      dueDate: iso(addDays(today, 2)),
      postponedCount: 0,
      postponeHistory: [],
      waitingOn: 'document',
      waitingReason: 'Autorisation municipale en cours de traitement',
      source: 'manual',
      createdAt: iso(subDays(today, 12)),
      updatedAt: iso(subDays(today, 12)),
    },
    {
      id: 't5',
      title: 'Obtenir la validation du devis fleuriste revu',
      status: 'en_attente',
      priority: 'normale',
      weddingId: 'w3',
      vendorId: 'v1',
      dueDate: iso(addDays(today, 1)),
      postponedCount: 0,
      postponeHistory: [],
      waitingOn: 'client',
      source: 'manual',
      createdAt: iso(subDays(today, 9)),
      updatedAt: iso(subDays(today, 9)),
    },
    {
      id: 't6',
      title: 'Préparer la checklist de montage du jour J',
      status: 'a_preparer',
      priority: 'normale',
      weddingId: 'w4',
      dueDate: iso(addDays(today, 5)),
      postponedCount: 0,
      postponeHistory: [],
      source: 'manual',
      createdAt: iso(subDays(today, 2)),
      updatedAt: iso(subDays(today, 2)),
    },
    {
      id: 't7',
      title: 'Signer le contrat photographe',
      status: 'terminee',
      priority: 'haute',
      weddingId: 'w2',
      dueDate: iso(subDays(today, 6)),
      completedAt: iso(subDays(today, 6)),
      postponedCount: 0,
      postponeHistory: [],
      source: 'manual',
      createdAt: iso(subDays(today, 30)),
      updatedAt: iso(subDays(today, 6)),
    },
  ]

  // w1 (dans 12 jours) porte volontairement 3 conflits réels pour la démo :
  // un chevauchement (installation florale / livraison traiteur), une marge
  // insuffisante avant l'arrivée du DJ, et une durée déclarée incohérente
  // sur le cocktail (60 min saisies pour un créneau réel de 30 min).
  const w1EventDate = iso(addDays(today, 12))
  const timelineEvents: Workspace['timelineEvents'] = [
    {
      id: 'ev1',
      weddingId: 'w1',
      title: 'Ouverture du lieu',
      date: w1EventDate,
      startTime: '08:00',
      endTime: '08:30',
      location: 'Domaine de la Prairie',
      type: 'jalon',
      status: 'confirme',
      isPhotoMoment: false,
      createdAt: iso(subDays(today, 40)),
      updatedAt: iso(subDays(today, 40)),
    },
    {
      id: 'ev2',
      weddingId: 'w1',
      title: "Arrivée de l'équipe décoration",
      date: w1EventDate,
      startTime: '09:00',
      endTime: '09:30',
      location: 'Domaine de la Prairie',
      type: 'jalon',
      status: 'prevu',
      isPhotoMoment: false,
      createdAt: iso(subDays(today, 40)),
      updatedAt: iso(subDays(today, 40)),
    },
    {
      id: 'ev3',
      weddingId: 'w1',
      title: 'Installation florale',
      date: w1EventDate,
      startTime: '11:00',
      endTime: '13:00',
      location: 'Domaine de la Prairie',
      type: 'jalon',
      status: 'prevu',
      isPhotoMoment: false,
      createdAt: iso(subDays(today, 35)),
      updatedAt: iso(subDays(today, 35)),
    },
    {
      id: 'ev4',
      weddingId: 'w1',
      title: 'Livraison traiteur',
      date: w1EventDate,
      startTime: '12:30',
      endTime: '13:30',
      location: 'Domaine de la Prairie',
      vendorId: 'v1',
      type: 'livraison_prestataire',
      status: 'prevu',
      isPhotoMoment: false,
      createdAt: iso(subDays(today, 35)),
      updatedAt: iso(subDays(today, 35)),
    },
    {
      id: 'ev5',
      weddingId: 'w1',
      title: 'Contrôle de la salle',
      date: w1EventDate,
      startTime: '14:00',
      endTime: '14:30',
      location: 'Domaine de la Prairie',
      type: 'jalon',
      status: 'prevu',
      isPhotoMoment: false,
      createdAt: iso(subDays(today, 20)),
      updatedAt: iso(subDays(today, 20)),
    },
    {
      id: 'ev6',
      weddingId: 'w1',
      title: 'Cocktail',
      date: w1EventDate,
      startTime: '16:00',
      endTime: '16:30',
      // Volontairement incohérente avec le créneau réel (30 min) pour illustrer la détection.
      durationMinutes: 60,
      location: 'Domaine de la Prairie',
      type: 'jour_j',
      status: 'prevu',
      isPhotoMoment: true,
      createdAt: iso(subDays(today, 20)),
      updatedAt: iso(subDays(today, 20)),
    },
    {
      id: 'ev7',
      weddingId: 'w1',
      title: 'Arrivée du DJ',
      date: w1EventDate,
      startTime: '17:00',
      endTime: '17:15',
      location: 'Domaine de la Prairie',
      vendorId: 'v2',
      type: 'jalon',
      status: 'a_verifier',
      isPhotoMoment: false,
      createdAt: iso(subDays(today, 20)),
      updatedAt: iso(subDays(today, 20)),
    },
    {
      id: 'ev8',
      weddingId: 'w1',
      title: 'Dîner',
      date: w1EventDate,
      startTime: '18:30',
      endTime: '22:00',
      location: 'Domaine de la Prairie',
      vendorId: 'v1',
      type: 'jour_j',
      status: 'prevu',
      isPhotoMoment: true,
      createdAt: iso(subDays(today, 20)),
      updatedAt: iso(subDays(today, 20)),
    },
    {
      id: 'ev9',
      weddingId: 'w1',
      title: 'Début du démontage',
      date: w1EventDate,
      startTime: '22:30',
      endTime: '23:30',
      location: 'Domaine de la Prairie',
      type: 'jalon',
      status: 'prevu',
      isPhotoMoment: false,
      createdAt: iso(subDays(today, 20)),
      updatedAt: iso(subDays(today, 20)),
    },
    {
      id: 'ev10',
      weddingId: 'w4',
      title: 'Cérémonie',
      date: iso(addDays(today, 8)),
      startTime: '15:00',
      endTime: '16:00',
      location: 'Le Clos des Cèdres',
      type: 'jour_j',
      status: 'confirme',
      isPhotoMoment: true,
      createdAt: iso(subDays(today, 30)),
      updatedAt: iso(subDays(today, 30)),
    },
  ]

  // "Autres dépenses" uniquement — les coûts fournisseurs vivent sur
  // vendorWeddingLinks (ci-dessus), jamais mélangés ici.
  const expenses: Workspace['expenses'] = [
    {
      id: 'e1',
      weddingId: 'w1',
      description: 'Location mobilier décoration',
      category: 'location',
      amount: 800,
      date: iso(subDays(today, 10)),
      status: 'payee',
      createdAt: iso(subDays(today, 10)),
      updatedAt: iso(subDays(today, 10)),
    },
    {
      id: 'e2',
      weddingId: 'w2',
      description: 'Location mobilier',
      category: 'location',
      amount: 600,
      date: iso(subDays(today, 15)),
      status: 'engagee',
      createdAt: iso(subDays(today, 15)),
      updatedAt: iso(subDays(today, 15)),
    },
    {
      id: 'e3',
      weddingId: 'w2',
      description: "Repas de l'équipe le jour J",
      category: 'repas',
      amount: 150,
      date: iso(addDays(today, 41)),
      status: 'prevue',
      createdAt: iso(subDays(today, 15)),
      updatedAt: iso(subDays(today, 15)),
    },
    {
      id: 'e4',
      weddingId: 'w3',
      description: 'Location salle supplémentaire pour le cocktail',
      category: 'location',
      amount: 3500,
      date: iso(subDays(today, 20)),
      status: 'engagee',
      createdAt: iso(subDays(today, 20)),
      updatedAt: iso(subDays(today, 20)),
    },
  ]

  // Couvre les 6 statuts : proposé (w1), à envoyer (w4), en attente
  // d'approbation (w3), approuvé (w1 et w2 — dont un geste commercial non
  // facturé pour tester le scope creep non facturé), rejeté (w1), réalisé (w4).
  const scopeChanges: Workspace['scopeChanges'] = [
    {
      id: 'sc1',
      weddingId: 'w1',
      description: 'Guirlandes lumineuses supplémentaires',
      date: iso(subDays(today, 3)),
      vendorCost: 150,
      clientPrice: 450,
      status: 'approuvee',
      createdAt: iso(subDays(today, 3)),
      updatedAt: iso(subDays(today, 2)),
    },
    {
      id: 'sc2',
      weddingId: 'w1',
      description: "Prolongation de la soirée d'une heure",
      date: iso(subDays(today, 1)),
      vendorCost: 300,
      clientPrice: 300,
      status: 'proposee',
      createdAt: iso(subDays(today, 1)),
      updatedAt: iso(subDays(today, 1)),
    },
    {
      id: 'sc3',
      weddingId: 'w1',
      description: 'Passage à un menu premium',
      date: iso(subDays(today, 6)),
      vendorCost: 600,
      clientPrice: 900,
      status: 'rejetee',
      notes: 'Client a refusé le surcoût.',
      createdAt: iso(subDays(today, 6)),
      updatedAt: iso(subDays(today, 5)),
    },
    {
      id: 'sc4',
      weddingId: 'w2',
      description: "Ajout d'une deuxième salle pour le vin d'honneur",
      date: iso(subDays(today, 4)),
      vendorCost: 450,
      clientPrice: 0,
      status: 'approuvee',
      notes: 'Geste commercial suite à un retard de livraison — non facturé.',
      createdAt: iso(subDays(today, 4)),
      updatedAt: iso(subDays(today, 3)),
    },
    {
      id: 'sc5',
      weddingId: 'w3',
      description: 'Supplément fleuriste pour le bouquet de la mariée',
      date: iso(subDays(today, 2)),
      vendorCost: 120,
      clientPrice: 250,
      status: 'en_attente_approbation',
      notes: 'En attente de retour du couple.',
      createdAt: iso(subDays(today, 2)),
      updatedAt: iso(subDays(today, 2)),
    },
    {
      id: 'sc6',
      weddingId: 'w4',
      description: "Ajout d'un feu d'artifice",
      date: iso(addDays(today, 1)),
      vendorCost: 500,
      clientPrice: 800,
      status: 'a_envoyer',
      createdAt: iso(addDays(today, 1)),
      updatedAt: iso(addDays(today, 1)),
    },
    {
      id: 'sc7',
      weddingId: 'w4',
      description: 'Retouche photo supplémentaire',
      date: iso(subDays(today, 30)),
      vendorCost: 80,
      clientPrice: 150,
      status: 'realisee',
      createdAt: iso(subDays(today, 30)),
      updatedAt: iso(subDays(today, 25)),
    },
  ]

  const clientDecisions: Workspace['clientDecisions'] = [
    {
      id: 'd1',
      weddingId: 'w2',
      subject: 'Choix du menu végétarien vs. mixte pour 90 invités',
      date: iso(subDays(today, 8)),
      dueDate: iso(addDays(today, 3)),
      pending: true,
    },
    {
      id: 'd2',
      weddingId: 'w3',
      subject: 'Validation du budget fleuriste revu à la hausse (+600€)',
      date: iso(subDays(today, 5)),
      dueDate: iso(addDays(today, 6)),
      pending: true,
    },
  ]

  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    businessConfig: {
      id: generateId(),
      companyName: 'Atelier Fleur de Lien',
      vatStatus: 'franchise_en_base',
      currency: 'EUR',
    },
    userProfile: {
      id: generateId(),
      displayName: 'Démonstration',
      onboarded: true,
    },
    weddings,
    vendors,
    vendorWeddingLinks,
    tasks,
    timelineEvents,
    expenses,
    scopeChanges,
    proposals: [],
    soldServices: [],
    proposalTemplates: createDefaultProposalTemplates(),
    clientDecisions,
    invoices: [],
    equipmentItems: [],
    closingSessions: [],
    uiPreferences: { theme: 'system' },
    ignoredConflictIds: [],
  }
}
